on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys 
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.9' 
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && exit "

    - name: run1
      run: echo "The value of MY_SECRET is: ${{ secrets.MY_SECRET }}"
    - name: run2
      run: cd ${{ secrets.WORK_DIR }} && python3 write.py
    - name: cleanup
      run: rm -rf ~/.ssh
